### ISSUE TITLE
Create SciRuby Guides

### ISSUE THREAD

**Issue by agarie** [SciRuby/sciruby#24]
This is an idea for when we have better documentation and development on the subprojects.

We could use guides showing how to use the various parts of SciRuby, e.g. how to solve linear systems, interpolation, statistics, etc. It'd be similar to [RailsGuides](http://guides.rubyonrails.org/).

I'll write something using NMatrix, but this should be done for all the projects and for various simple recurrent problems.

Obs: This is the same as saying "we need better documentation". We need better documentation. Even the examples on [statsample](https://github.com/SciRuby/statsample/tree/master/examples) and the specs on nmatrix, distribution, etc aren't enough.

**Comment by stardiviner** [comment]
+1

**Comment by patrickjonesdotca** [comment]
:+1:

**Comment by minad** [comment]
I think we can achieve this using iruby notebooks, see https://github.com/SciRuby/sciruby-notebooks

**Comment by stardiviner** [comment]
@minad great idea.

**Comment by agarie** [comment]
That's good. This issue can -- finally -- be closed.
