### ISSUE TITLE
Transfer iruby to sciruby?

### ISSUE THREAD

**Issue by minad** [SciRuby/sciruby#33]
Hi would you be interested in that? I still want to continue to maintain it, but maybe it is better to transfer it to your organization?

**Comment by minad** [comment]
I converted the readme to fulfill the guidelines. Maybe transfer it now before the gsoc starts?

**Comment by mohawkjohn** [comment]
Yes! Can do. =) On it right now.

**Comment by minad** [comment]
Can you also activate the issues there and add me as a contributor? I would like to transfer the issues here. domitry and agarie had also access to my repo, you might want to add them too.

**Comment by mohawkjohn** [comment]
Are you sure you don't have access? I added you as an admin earlier today.

**Comment by mohawkjohn** [comment]
Yeah, you have to accept the invite.
