### ISSUE TITLE
Page not found on a link in GSoC 2015 ideas wiki

### ISSUE THREAD

**Issue by abinashmeher999** [SciRuby/sciruby#34]
I was going through the [Google Summer of Code 2015 Ideas](https://github.com/SciRuby/sciruby/wiki/Google-Summer-of-Code-2015-Ideas) and found that the link [Finding The SciRuby Development Repositories on Github](https://thismagpie.com/finding-the-sciruby-development-repositories-on-github) under the heading [Read this before you commit your first patches](https://github.com/SciRuby/sciruby/wiki/Google-Summer-of-Code-2015-Ideas#read-this-before-you-commit-your-first-patches) shows an error 404: not found. Thought it would be better to bring this to your notice since a lot of students would be visiting this page.

**Comment by mohawkjohn** [comment]
Thanks so much for pointing this out! The link has been fixed now.
