### ISSUE TITLE
What is the purpose of this gem?

### ISSUE THREAD

**Issue by minad** [SciRuby/sciruby#36]
There is some code which hasn't been changed since 2011. Why is that? Shouldn't this be some kind of meta gem?

Is there a list of all sci gems that are currently under development?

**Comment by agarie** [comment]
I agree with you, it should. I guess we focused on NMatrix and forgot about this one. I'm OK with maintaining it such that `require 'sciruby'` allows someone to use NMatrix, Distribution, Integration, Minimization and Statsample together. What do you think? @mohawkjohn?

Also, we need to put a list of the gems under development on the [sciruby.com](http://sciruby.com) website.

**Comment by mohawkjohn** [comment]
Sure. Do whatever you want with this gem. :) I'm not attached to it.

**Comment by minad** [comment]
Take a look what I wrote in #37

**Comment by minad** [comment]
@agarie list of gems is now in gems.yml maybe we can use that for the homepage
