### ISSUE TITLE
sciruby-plotter and old code

### ISSUE THREAD

**Issue by minad** [SciRuby/sciruby#39]
Hi @mohawkjohn,

I just closed all the old issues concerning the sciruby-plotter and the sciruby tool. I am wondering about it and the work that went into it - should we copy the code to some subproject or was everything somehow reused/scattered over the various gems that we have now? Maybe you would also like to keep it somewhere for historical reasons? ;)

**Comment by minad** [comment]
I put it here for now: https://github.com/SciRuby/legacy-sciruby-ide

**Comment by mohawkjohn** [comment]
Hey, thanks, that works. Yeah, I don't think it'll be too useful for many people, but good to keep a copy somewhere.
