### ISSUE TITLE
Update list of gems

### ISSUE THREAD

**Issue by minad** [SciRuby/sciruby#40]
The list of gems is kept in the gems.yml

* Add version constraints (version: '~> ...')
* Remove obsolete gems
* Add missing gems
* Improve descriptions
* Improve categories
* Test all gems, autoloading of modules etc.

ping @SciRuby/owners

**Comment by minad** [comment]
See https://gist.github.com/agarie/272ef4967479fedac856

cc @agarie

**Comment by agarie** [comment]
Hah! I made that list last year, so it is outdated. The idea is exactly what you're doing with the `sciruby` gem. :balloon:
