### ISSUE TITLE
add link to gems.sciruby.com to website

### ISSUE THREAD

**Issue by minad** [SciRuby/sciruby#42]
ping @audy

**Comment by audy** [comment]
@mohawkjohn it looks like the Octopress source hasn't been updated but the sciruby.github.com repo has. Is there a fork of the Octopress source kickin' around?

**Comment by mohawkjohn** [comment]
Yeah, it's http://github.com/SciRuby/sciruby.com you're looking for. `source` branch! Not master!

**Comment by minad** [comment]
see https://github.com/SciRuby/sciruby.com/pull/38

**Comment by mohawkjohn** [comment]
Oops! Got it. Thanks.

Yes, also pushed to source.

**Comment by minad** [comment]
thx
