### ISSUE TITLE
conflicting dependency on install

### ISSUE THREAD

**Issue by badbabykosh** [SciRuby/sciruby#49]
$ gem install sciruby-full
ERROR:  While executing gem ... (Gem::DependencyResolutionError)
    conflicting dependencies nmatrix (= 0.2.0) and nmatrix (~> 0.1)
  Activated nmatrix-0.1.0 via:
    nmatrix-0.1.0 (~> 0.1), sciruby-full-0.2.8 (= 0.2.8)
  instead of (= 0.2.0) via:
    nmatrix-lapacke-0.2.0 (~> 0.2.0), mixed_models-0.1.1 (~> 0.1), sciruby-full-0.2.8 (= 0.2.8)

**Comment by minad** [comment]
should work again
