### ISSUE TITLE
Algorithms gem

### ISSUE THREAD

**Issue by Sayanc93** [SciRuby/sciruby#51]
Why do we need a forked gem for algorithms and DS implementation?
Can't Sciruby build this on its own? I'm sure it'll be more optimised.
I looked into the gem and saw ruby handling all the code for all the algorithms and DS. A C library handling the processing for the input will be much better I think, since Sciruby is meant to work for small and large datasets.
I can help contribute building it, if needed.

BTW kudos to the maintainers for building this meta-gem 👍

**Comment by translunar** [comment]
DS? Can you be clear about _which_ algorithms?
