### ISSUE TITLE
feature request - move development discussion to Gitter

### ISSUE THREAD

**Issue by MatthewSteen** [SciRuby/sciruby#53]
Since development is done on GitHub, I suggest using https://gitter.im/home/ as a discussion platform. It's very similar to Slack but without the limits on the number of users or messages. The Jupyter project is very active there and Daru has a "room" there as well (https://gitter.im/v0dro/daru). Like Slack, it offers a great platform for developers and users to communicate in real-time. A room could be created for each SciRuby repo or more if needed.

**Comment by bekicot** [comment]
@MatthewSteen Agree. There is already existing room for SciRuby/nmatrix .

**Comment by Nakilon** [comment]
BTW the Search in Gitter sucks. It just doesn't find things unless you include multiple matching words at a time.
Since the 2017 the Github Discussions appeared -- they are more informative for people who see the project the first and just want to take a look about questions and problems discussed.

**Comment by MatthewSteen** [comment]
> 
> 
> BTW the Search in Gitter sucks. It just doesn't find things unless you include multiple matching words at a time.
> Since the 2017 the Github Discussions appeared -- they are more informative for people who see the project the first and just want to take a look about questions and problems discussed.

@Nakilon thanks for the Gitter feedback. However, I don't see `Discussions` here. Perhaps the owners have to enable it.

**Comment by Nakilon** [comment]
> Perhaps the owners have to enable it

Yes, it is in the repo settings.

**Comment by pjotrp** [comment]
We actually moved to freenode+matrix. But now freenode has had a hostile takeover we don't really have a space. Let me create a matrix room. Matrix rocks :). I created a public room #sciruby:matrix.org. Feel free to join.

You may use https://matrix.to/#/!MLbAvCRTMqzQaCzjvJ:matrix.org?via=matrix.org

**Comment by Nakilon** [comment]
There is no evidence of a "hostile takeover". People are running to Libera away from their own demons in heads that don't like that someone is Korean )

**Comment by pjotrp** [comment]
You can find us on matrix or IRC libera.chat #sciruby.
