### ISSUE TITLE
sciruby-full fails to install on Ubuntu 18.04

### ISSUE THREAD

**Issue by lokeshh** [SciRuby/sciruby#55]
Here's the log https://gist.github.com/lokeshh/2965832ed4f1cb718723bfe2b709a6af

The Dockerfile I used:

```Docker
FROM jupyter/base-notebook:latest

USER root

RUN apt-get update && \
    apt-get install -y build-essential \
        ruby2.5 ruby2.5-dev libzmq3-dev gnuplot-nox libgsl-dev libtool autoconf make \
        automake zlib1g-dev libsqlite3-dev libmagick++-dev imagemagick \
        libatlas-base-dev g++ libczmq-dev libffi-dev libtool-bin cmake git && \
        apt-get clean

# See https://github.com/methodmissing/rbczmq/issues/64
RUN CPPFLAGS='-Wno-error=deprecated-declarations' gem install rbczmq -v '1.7.9'

RUN gem update --no-document --system && gem install --no-document sciruby-full

USER $NB_UID

RUN iruby register --force

COPY . .

ENTRYPOINT jupyter-notebook
```

It seems to me the problem is with `gsl` gem.

**Comment by lokeshh** [comment]
What's the command to install `sciruby-full` from this repository after making some changes? @v0dro ?

**Comment by Shekharrajak** [comment]
It looks like gsl gem have dependencies : [Installation instruction](https://github.com/SciRuby/rb-gsl#installation). So I guess `gsl-bin libgsl0-dev libgsl0-dbg` are missing.

**Comment by lokeshh** [comment]
I don't think that's the case because `gem install gsl` installs the gem
without an error.
