### ISSUE TITLE
Migrate mrkn/iruby-rails to sciruby/iruby-rails

### ISSUE THREAD

**Issue by mrkn** [SciRuby/sciruby#56]
Hi all,

I have [iruby-rails](https://github.com/mrkn/iruby-rails).  It is a small gem that provides the function to load Rails application environment in a session of IRuby.

I want to migrate this small gem to SciRuby organization.

How do you think about that?

**Comment by v0dro** [comment]
Sure. Do you have repo creation access to sciruby?

**Comment by mrkn** [comment]
> Do you have repo creation access to sciruby?

No.  When I tried to migrate the repo, GitHub said "You don’t have the permission to create repositories on SciRuby".

**Comment by prasunanand** [comment]
I tried adding @mrkn to members. I couldn't add him. @mohawkjohn can help. Also @shekharrajak needs to be added to `daru-developers` team in SciRuby org.

**Comment by v0dro** [comment]
@mrkn has been sent an invite. I have also send an invite to @Shekharrajak and added him to daru-developers.

**Comment by mrkn** [comment]
@v0dro Thank you!!

**Comment by mrkn** [comment]
I've migrated the repository.
