### ISSUE TITLE
Liveness of this project

### ISSUE THREAD

**Issue by javadba** [SciRuby/sciruby#57]
Assuming this project is moribund.. too bad Ruby crushes python.

**Comment by pjotrp** [comment]
Not quite true. Activity is in the other modules in https://github.com/SciRuby. There is quite a bit of work going on with CUDA and math. And I agree, Ruby is superior to Python in almost every way.

**Comment by javadba** [comment]
oh! Thanks for the pointer to that "home page" .  I'm going to see if can find a viable environment with:
 - usable dataframe
 - reasonable stats summarization
 - basic linear and random forest algos
 - plotting/ dataviz

That  would constitute a workable environment for initial exploratory data analysis.  Just browsing through those seem to be at least partially addressed in:

 - daru
- rubyplot /nyaplot
- statstample, distribution, rb-gsl

Pretty exciting - will do test drive in a few weeks after I get out from under red hot deadlines.

**Comment by pjotrp** [comment]
Best to join the sciruby mailing list too.

**Comment by kojix2** [comment]
Don't forget NArray family.

* [Numo::NArray](https://github.com/ruby-numo/numo-narray)
* [Cumo](https://github.com/sonots/cumo) <- CUDA
* [SVMKit](https://github.com/yoshoku/SVMKit) <- random forest algos

**Comment by javadba** [comment]
SVMKit looks delicious

Am Do., 21. Feb. 2019 um 22:43 Uhr schrieb kojix2 <notifications@github.com

**Comment by LeFnord** [comment]
… one want to make its hands dirty, where is a good point to start?

**Comment by diam** [comment]
With a binding for Julia (which crushes python too) ?

-- Maurice

**Comment by kojix2** [comment]
For Julia and Python bindings, [mrkn](https://github.com/mrkn) is working on [pycall.rb](https://github.com/mrkn/pycall.rb) and ruby-julia, but [ruby-julia](https://github.com/mrkn/ruby-julia) has not been committed recently.

**Comment by diam** [comment]
Thanks for the link on ruby-julia. Too bad it is no longer maintained.
In the meantime, I went to Julia for the scientific code.

-- Maurice
